### ISSUE TITLE
What is the role of Stage 1

### ISSUE THREAD

**Issue by NanAlbert** [jiaosiyu1999/MAFT#4]
This is an interesting work! 
It appears that Stage 1 is designed to train a model capable of generating masks for Stage 2. Beyond supplying masks for Stage 2's MAFT training, does Stage 1 serve any additional purposes? If not, what is the reason behind training a model in Stage 1 instead of directly utilizing pre-trained models like FreeSeg or Mask2Former?
Thank you!

**Comment by jiaosiyu1999** [comment]
Thanks for your attention. The viewpoint that "Stage 1 is designed to train a model capable of generating masks for Stage 2" is correct. 

We retrained FreeSeg because the official implementation of FreeSeg differs from the standard OV-Seg settings: FreeSeg is trained with the unified semantic, instance, and panoptic labels, whereas  OV-Seg models are trained only on COCO-Stuff. 
Of course, you can also use other pre-trained models, _e.g._, SAM or MaskFormer, to generate masks.
